### ISSUE TITLE
Incorrect saving of floating point numbers

### ISSUE THREAD

**Issue by Hancapo** [citizenfx/AnimKit#1]
System:
Windows 11 Pro x64
Region: `es-CL`

AnimKit.UI version used: `v1.0.3`

I found a bug with the decimal numbers when I try to add a `Used animation` to a Clip in the `Clips` tab, the numbers show correctly the first time, but if I go to another tab and go back to the `Clip` tab the numbers are broken.

[![Image from Gyazo](https://i.gyazo.com/7bdbe892cc4aa77d91cfdfe2f62a3148.gif)](https://gyazo.com/7bdbe892cc4aa77d91cfdfe2f62a3148)

I fixed this entirely by editing `App.xaml.cs` adding the following line of code within `App_startup` method

`Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;`

**Comment by Disquse** [comment]
Thanks for this report. I will take a look on the described issue soon.
