### ISSUE TITLE
Cant load animation as asset after exported the same animation.

### ISSUE THREAD

**Issue by leostmc1** [citizenfx/AnimKit#2]
AnimKit keeps importing and never advances, first I converted a ycd to an asset and then without touching anything I exported that asset again as a ycd with another name, when trying to import the final ycd the program simply keeps loading forever.

**Comment by Disquse** [comment]
Hey! There's not enough information to even start researching possible reasons. Provide your assets (that affected by this bug) so we can reproduce this issue. As multiple exporting/importing were tested and working as it should. So it is possible that something going wrong under unknown circumstances,

**Comment by leostmc1** [comment]
Hi sorry for late response, I've been figuring out the problem and managed to specify it quite a bit, by taking a dictionary with animations that have hashes, exporting one of the animations and then importing it again replacing itself (without any editing) then the game crashes. For this I am creating an addon dictionary and calling it through weaponsanimations.meta, the file call is correct because if I just change the name of the dictionary and call it, then everything is correct, therefore with that I rule out that the declaration of the dictionary and the call are wrong, the detail as I told you is when editing one of the animations from the dictionary and putting it in the game, this crashes the game. You can try with the dictionary "weapons@rifle@hi@sniper_rifle". Maybe we could get in touch, so I can show you the problem faster.
